# Generated by Django 6.0.5 on 2026-06-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_risk_threshold', models.FloatField(default=50)),
                ('medium_risk_threshold', models.FloatField(default=75)),
            ],
        ),
    ]
