# Generated by Django 6.0.5 on 2026-06-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_riskthreshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='recommendation_reason',
            field=models.TextField(blank=True),
        ),
    ]
